### PR TITLE
Add possibility to disable plugin

### PR DESCRIPTION
**Pull request by zitscher**
We'd like to only add the plugin on our Production build, thus the PR. Thanks!

### CODE REVIEW

**Comment by daliborgogic** [comment]
@zitscher Make sense. Thank you on PR.

**Comment by zitscher** [comment]
Thanks, very much appreciated!

**Comment by zitscher** [comment]
Could I also please ask you to update your npm package? Many thanks!

**Comment by daliborgogic** [comment]
@zitscher of course

**Comment by daliborgogic** [comment]
@zitscher published on `npm` 🚀

**Pull request merged**
